apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"azure-vote-front","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"azure-vote-front"}},"template":{"metadata":{"labels":{"app":"azure-vote-front"}},"spec":{"containers":[{"env":[{"name":"REDIS","value":"azure-vote-back"}],"image":"mcr.microsoft.com/azuredocs/azure-vote-front:v1","name":"azure-vote-front","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2022-05-10T00:16:31Z"
  generation: 4
  name: azure-vote-front
  namespace: default
  resourceVersion: "3270483"
  uid: 4551fcd9-64c0-4acb-812c-0276319da4c0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: azure-vote-front
    spec:
      containers:
      - env:
        - name: REDIS
          value: azure-vote-back
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        imagePullPolicy: IfNotPresent
        name: azure-vote-front
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-10T00:16:31Z"
    lastUpdateTime: "2022-05-10T00:16:53Z"
    message: ReplicaSet "azure-vote-front-85b4df594d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-17T05:03:22Z"
    lastUpdateTime: "2022-05-17T05:03:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
    minReplicas: 1
  maxReplicas: 10
  metrics:
    - resources:
        name: cpu
        targetAverageUtilization: 5
      type: resources
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-vote-front
